### ISSUE TITLE
YAML contain PY files?

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#15]
Hey guys just wondering if our env file should contain the 3 py files? I think it's ok based on what were working on and doesn't bloat anything - curious what you guys think.

**Comment by fohy24** [comment]
We might want to explore into other models and methods that are more easily done in Python in the future. I believe it is realistic to have it installed and prepared in the env.
