### ISSUE TITLE
We might need to upload our data and make a data/ folder

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#16]
I know we aren't using any local data and our data is accessed through a library, but we might need download the data from the titanic package and include it.

**Comment by fohy24** [comment]
Yes that would be nice to anyone trying to contribute

**Comment by Sampsonyu** [comment]
that is a good point. Issue has been fixed
