### ISSUE TITLE
How do we create a container?

### ISSUE THREAD

**Issue by fohy24** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#20]
do we docker run this? https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/tidyverse_devel.Dockerfile

**Comment by alanpow** [comment]
That looks like the right things to follow as a pre built

**Comment by alanpow** [comment]
I will "docker run --rm -it rocker/rstudio:devel"

**Comment by alanpow** [comment]
<img width="742" alt="image" src="https://github.com/UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis/assets/83424099/a6c571f9-7cab-4ebd-b2be-a73af0f609a1">
This is what I get

**Comment by alanpow** [comment]
Scratch that, I am going to work with this container [jupyter/r-notebook](https://github.com/jupyter/docker-stacks/blob/main/images/r-notebook/Dockerfile). It is from the individual assignment notes: 
<img width="511" alt="image" src="https://github.com/UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis/assets/83424099/317af9fe-640e-4155-891b-dd746df19fa1">

**Comment by karan-khubdikar** [comment]
Yes, I guess we can use this docker image and build up on it.

**Comment by Sampsonyu** [comment]
Yes since we are using R kernel in jupyter notebook, this image looks good!
