### ISSUE TITLE
Report into functions

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#22]
Hey guys let's set up a call in the next few minutes to organize how are are going to cut up our report and organize it into functions. We can then work on setting up the tests.

**Comment by alanpow** [comment]
I looked through our past report and saw we have:

1. Data wrangling where we selected the columns of interest, where we bin the age ranges and select them as the column, and where we factor the categorical columns.
2. We have our EDA where we produce the graphs, mainly making distributions and coloring them by the target values.
3.  Making the linear regression model
4. Organizing the outputs of the linear regression model into a nice formatted table

Each other these parts can be made into 1-3 possible functions.

**Comment by karan-khubdikar** [comment]
Done and dusted!

**Comment by fohy24** [comment]
Function for the regression model is also done!

**Comment by alanpow** [comment]
awesome I saw that Karan made the EDA functions and I completed the data wrangling functions :)
