### ISSUE TITLE
Week 3 Lab Meeting

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#38]
Here are some notes and ideas we made for converting our Milestone 2 to the requirements of Milestone 3. 

Parts of our data we need to turn into scripts:
1. Loading and saving the titanic data, save it locally to **/data/raw**
2. Make a script for running the wrangling functions (select and clean) then save output to **/data/processed**
3. Make a script that runs the EDA plotting functions, one for the Financial Info Plot and one for the Personal Attributes plot, then save as a PNG to **/results/figures**
4. Make a script that runs the GLM() fitting, then saves that object as a .rds to **/results/models**
5. Make script that runs the summary table creation accessing the .rds, then outputs/saves the .csv tidy table to **/results/tables**

Then we need to then update our .ipynb to not have any code, but just call the .csv and .png outputs we made with our scripts from the /results and /data folders. Also create a script that allows someone to run and export our .ipynb as a pdf.

**Comment by karan-khubdikar** [comment]
Thanks for summarizing this up, Alan. Let's try making the scripts for the functions that each one of us wrote initially for the first milestone.

**Comment by fohy24** [comment]
Thanks Alan. I can take item 4. Maybe we can finish our .ipynb when we meet on Friday

**Comment by Sampsonyu** [comment]
That is a good plan. Thanks, Alan!
I will be working on item 5

**Comment by alanpow** [comment]
Awesome looks like we'll have everyone focus on making scripts and results/data for their corresponding functions from Milestone 2 :)
