### ISSUE TITLE
Sourcing Functions in Script

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#40]
Hey good meeting today guys, as per Karan's finding from attending the Office Hour I just want to remind everyone that we are not recreating our functions in our scripts, but rather we are sourcing our existing .R function files and calling our functions in our scripts for command line applications. :) Thanks Karan! Let me know how you guys are feeling about everything/where everyones at!

**Comment by Sampsonyu** [comment]
Thanks for the reminder. I have updated my script to source functions we have created in milestone 2

**Comment by karan-khubdikar** [comment]
Thanks Alan for creating the issue for this. I have updated my script file and created a branch for the same. We can update the report once we have all the necessary script files and wrap up the part 1 of Milestone 3

**Comment by fohy24** [comment]
Thanks everyone! My script is also merged with the main branch

**Comment by karan-khubdikar** [comment]
Closing this issue as we are done with the scripts.
