### ISSUE TITLE
Here are the commands I am running in command line to run my scripts! Lets add them here for Readme

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#46]
Rscript scripts/column_selection_script.R "data/Processed/selected_columns.csv"

Rscript scripts/clean_and_organize_script.R "data/Processed/selected_columns.csv" "data/Processed/clean_wrangled_titanic_data.csv"

**Comment by karan-khubdikar** [comment]
Here is the command for my section 

Rscript scripts/EDA_scripts.R --dataset=data/Processed/clean_wrangled_titanic_data.csv --out_dir=results/plots/
