### ISSUE TITLE
Environment yml file

### ISSUE THREAD

**Issue by karan-khubdikar** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#6]
Hey guys,
I have created an environment yaml file and added the packages that I feel are necessary. Please feel free to download and create the environment on your local system and let me know if it works or if i need to make some edits.

**Comment by fohy24** [comment]
Part of the installation have failed on my Windows machine. Some packages are not installed but the main functions seem to be working. Anyone also experiencing the same issue?

Here is the error code:

$ conda env create --file environment.yaml
Channels:

defaults
conda-forge
r
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: / C:\Users\fohy2\miniconda3\envs\522_group4_M1\Lib\site-packages\nb_conda_kernels\install.py:8: Deprl
from pkg_resources import iter_entry_points
Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\fohy2\miniconda3\envs\522_group4_M1
Status: enabled

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\Users\fohy2\miniconda3\envs\522_group4_M1\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\Users\fohy2\gi]
Pip subprocess output:

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement t (from versions: none)
ERROR: No matching distribution found for t

failed

CondaEnvException: Pip failed

**Comment by alanpow** [comment]
It was fine for me but I heard another group had some weird stuff happening with pip? Maybe check that out since thats what the error says.

**Comment by karan-khubdikar** [comment]
Sure. Ill look into it.

**Comment by Sampsonyu** [comment]
it works for me as well

**Comment by karan-khubdikar** [comment]
I have fixed the issue. Let me know if it works now Sam.

**Comment by alanpow** [comment]
What was the fix?

**Comment by fohy24** [comment]
Thanks Karan, it worked. The fix is to remove the 'pip' of 'titanic' which should be installed via R package.
