### ISSUE TITLE
<Peer-Review-Issue>: Docker File

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#62]
Hina spoke to me in lecture today and was unable to get our docker container to work, however, one person in the comments said it did work... So I am not sure what the issue is since it can't be operating system if our team has both windows and apple... Any ideas?

**Comment by Sampsonyu** [comment]
I just tried it again on my MacBook with m1 chip. It works. Can anyone else try it on other systems?

**Comment by karan-khubdikar** [comment]
I guess we all can try to run it once from our laptops and if it works then it probably could be some issue with specific systems. But we could check with Tiffany regarding it.

**Comment by Sampsonyu** [comment]
Based on our investigation, I think the docker compose issue is not reproducible
