### ISSUE TITLE
<Peer-Review-Issue>: Documentation and Project Information

### ISSUE THREAD

**Issue by Sampsonyu** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#63]
- Need for more detailed information in the About/Summary sections, similar to exemplar projects.
- Lack of clear project objectives, conclusions, and methods in the documentation.

**Comment by alanpow** [comment]
Got it

**Comment by Sampsonyu** [comment]
Closing the issue as it has been addressed in the pr
