### ISSUE TITLE
<Peer-Review-Issue>: Report Formatting 

### ISSUE THREAD

**Issue by Sampsonyu** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#64]
- Absence of numbering for tables and equations in the report.
- Missing table numbers in the final report for logistic regression results.
- Missing cross-references for figures within the text.

**Comment by alanpow** [comment]
I will look into this and get this done - I'm not too sure about the table and equation numbering, I would prioritize others changes as using glue we can only specify them as 'Fig' and they are actually Tables and Equations - so this personally I think would take away from the report.
