### ISSUE TITLE
README About Section Update

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#73]
I will also add more information to our About section in our README as per this peer review comment: "More details about the project should be included in the About/Summary sections. For example, the About section in Tiff's repo https://github.com/ttimbers/breast_cancer_predictor_py has the research objective, conclusions and methods briefly mentioned which gives me as a reader a quick overview of project details i.e. what the project is about, what they found and how they found it. In your case, including these points in the section would be very helpful."

**Comment by karan-khubdikar** [comment]
Thanks Alan!
