### ISSUE TITLE
Selecting features for model - dropping some?

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#8]
Hey guys I decided to drop the very unique variables such as ticket number, name, and passenger ID I think they're to unique and would cause overfitting also if we were ever to predict with this model it might not be wise to use these - might not translate to other boating accidents "Sandstrom, Miss. Marguerite Rut" is probably not on any other boats...

**Comment by alanpow** [comment]
My latest PR reflects what I did in the Selecting Features block of text

**Comment by fohy24** [comment]
I agree - unique identifiers are not helpful and give no/little explanatory power.

**Comment by karan-khubdikar** [comment]
I agree with dropping the unique identifiers. Other columns which are selected to fine to me.

**Comment by Sampsonyu** [comment]
I concur with the decision to drop the unique identifiers. Additionally, the other selected columns seem appropriate to me.

**Comment by alanpow** [comment]
Awesome lets leave it as it is then!
