### ISSUE TITLE
Renaming the REPO - Titanic related?

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#9]
Hey guys I think the milestone 1 instructions require us to set a repo name that is related to our analysis? Maybe something like "What Effects One Chance of Survival on the Titanic - A Logistic Regression Analysis" would be good, if anyone knows how to do it go for it :)

**Comment by karan-khubdikar** [comment]
Yes. Thanks for the reminder Alan! We should do the renaming before the submission.

**Comment by Sampsonyu** [comment]
That is a good point. I have renamed the repo

**Comment by Sampsonyu** [comment]
Closing the issue as it has been fixed
